CREATE TABLE USERS (
USER_INDEX INT NOT NULL PRIMARY KEY IDENTITY(1,1),
USER_ID VARCHAR(50) NOT NULL UNIQUE,
USER_NICKNAME VARCHAR(50) NOT NULL UNIQUE,
USER_PASSWORD VARCHAR(50) NOT NULL,
USER_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE DIARIES(
DIARY_INDEX INT NOT NULL PRIMARY KEY  identity(1,1),
DIARY_NAME VARCHAR(50) NOT NULL,
DIARY_PASSWD VARCHAR(8) NOT NULL,
CREATER_INDEX INT NOT NULL,
CONSTRAINT FK_USERS_DIARIES FOREIGN KEY (CREATER_INDEX) REFERENCES USERS (USER_INDEX)
ON UPDATE CASCADE
ON DELETE NO ACTION
);

CREATE TABLE COLLABORATERS(
USER_INDEX INT NOT NULL,
CONSTRAINT FK_USERS_COLLABORATERS FOREIGN KEY (USER_INDEX) REFERENCES USERS (USER_index)
ON DELETE CASCADE,
DIARY_INDEX INT NOT NULL,
CONSTRAINT FK_DIARIES_COLLABORATERS FOREIGN KEY (DIARY_INDEX) REFERENCES DIARIES (DIARY_INDEX)
ON DELETE CASCADE,
PRIMARY KEY(USER_INDEX, DIARY_INDEX),
WRITER_ORDER INT NOT NULL DEFAULT 1
);

CREATE TABLE PAPER(
PAPER_INDEX INT NOT NULL PRIMARY KEY,
CREATER_INDEX INT NOT NULL,
CONSTRAINT FK_USERS_PAPERS FOREIGN KEY (CREATER_INDEX) REFERENCES USERS (USER_INDEX)
ON DELETE CASCADE,
CREATED_DATE DATETIME NOT NULL DEFAULT(GETDATE()),
CONTENT VARCHAR(5000) NULL,
TITLE VARCHAR(100) NOT NULL,
DIARY_INDEX INT NOT NULL,
CONSTRAINT FK_DIARIES_PAPERS FOREIGN KEY (DIARY_INDEX) REFERENCES DIARIES (DIARY_INDEX)
ON DELETE CASCADE
);

CREATE TABLE WRITE_ORDER(
DIARY_INDEX INT PRIMARY KEY,
CONSTRAINT FK_DIARIES_ORDER FOREIGN KEY (DIARY_INDEX) REFERENCES DIARIES (DIARY_INDEX)
ON DELETE CASCADE,
COLLABO_NUM INT NOT NULL DEFAULT 1,
CURRENT_NUM INT NOT NULL DEFAULT 1,
);



